/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    id: 'vbox',
                    autoScroll: true,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: 'My Panel',
                    listeners: {
                        add: {
                            fn: me.onVboxAdd,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onVboxAdd: function(container, component, index, eOpts) {
        var editor = new Ext.Editor({
            updateEl: true, // update the innerHTML of the bound element when editing completes
            field: {
                xtype: 'combobox'
            }
        });

        if (!this.t) {


            this.t=Ext.Function.createBuffered(function(){
                Ext.Function.defer(function(){Ext.each(Ext.query('div.tutu'), function(el){
                    console.log(el)
                    Ext.get(el).on('click',function(){
                        editor.startEdit(this)
                    });
                })}, 1000);
            }, 5)
        }

        this.t();

    }

});