/*
 * File: app/view/testPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.testPanel', {
    extend: 'Ext.panel.Panel',

    height: 68,
    width: 746,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    height: 223
                },
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    hideHeaders: true,
                    store: 'user',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Name',
                            editor: {
                                xtype: 'textfield'
                            }
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.BufferedRenderer', {

                        }),
                        Ext.create('Ext.grid.plugin.CellEditing', {

                        })
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});