/*
 * File: app/view/toto.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.toto', {
    extend: 'Ext.view.View',

    height: 30,
    width: 400,
    itemSelector: 'div.tutu',
    store: 'user',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            itemTpl: [
                '<div class="tutu">{name}</div>'
            ]
        });

        me.callParent(arguments);
    }

});